import type { BannerDesign } from "@/types/banner";
import { Kookmin0 } from "@/components/banners/Kookmin0";
import { Minju0 } from "@/components/banners/Minju0";

// 현수막 디자인 목록
export const BANNER_DESIGNS: BannerDesign[] = [
  {
    id: "design-1",
    name: "국민 0",
    component: Kookmin0,
    width: 2560, // 3000mm = 3m
    height: 314, // 1000mm = 1m
    viewBox: "0 0 2560 314",
    editableAreas: [
      {
        id: "text1",
        name: "텍스트 1",
        type: "text",
        x: 37.3,
        y: 269,
        width: 800,
        height: 166.9,
        defaultValue: "발목잡힌 민생입법",
        className: "st1",
        transform: "translate(37.3 269)",
      },
      {
        id: "text2",
        name: "텍스트 2",
        type: "text",
        x: 1368.6,
        y: 269,
        width: 800,
        height: 166.9,
        defaultValue: "일하고 싶습니다",
        className: "st3",
        transform: "translate(1368.6 269)",
      },
      {
        id: "text3",
        name: "텍스트 3",
        type: "text",
        x: 1398.7,
        y: 98.7,
        width: 400,
        height: 78.3,
        defaultValue: "국민의힘",
        className: "st2",
        transform: "translate(1398.7 98.7)",
      },
      {
        id: "text4",
        name: "텍스트 4",
        type: "text",
        x: 42.5,
        y: 98.7,
        width: 400,
        height: 78.3,
        defaultValue: "못참겠다!",
        className: "st2",
        transform: "translate(42.5 98.7)",
      },
      {
        id: "text5",
        name: "텍스트 5",
        type: "text",
        x: 1671.6,
        y: 100.3,
        width: 200,
        height: 69.8,
        defaultValue: "은",
        className: "st5",
        transform: "translate(1671.6 100.3)",
      },
    ],
    preview: "brown-gradient-1",
  },
  {
    id: "design-2",
    name: "민주 0",
    component: Minju0,
    width: 3840,
    height: 650,
    viewBox: "0 0 3840 650",
    editableAreas: [
      {
        id: "text1",
        name: "제목",
        type: "text",
        x: 340.1,
        y: 168.7,
        width: 800,
        height: 138,
        defaultValue: "국민과 함께",
        className: "st2",
        transform: "translate(340.1 168.7)",
      },
      {
        id: "text2",
        name: "정당명",
        type: "text",
        x: 3104.3,
        y: 342.1,
        width: 600,
        height: 179.8,
        defaultValue: "민주당",
        className: "st3",
        transform: "translate(3104.3 342.1)",
      },
      {
        id: "text3",
        name: "지역명",
        type: "text",
        x: 3107.6,
        y: 454.9,
        width: 500,
        height: 88.5,
        defaultValue: "서울특별시당",
        className: "st0",
        transform: "translate(3107.6 454.9)",
      },
      {
        id: "text4",
        name: "슬로건",
        type: "text",
        x: 290,
        y: 543.6,
        width: 2000,
        height: 393.9,
        defaultValue: "새로운 대한민국!",
        className: "st1",
        transform: "translate(290 543.6)",
      },
    ],
    preview: "blue-gradient-1",
  },
];
